### ISSUE TITLE
Kinds

### ISSUE THREAD

**Issue by szaghi** [nicolasessisbreton/fython#1]
Dear Nicolas,

Great project, my best compliments :clap: 

I have already sent a replay on your google clf thread. Here have a question about varisble kind definition:

> which are the Fortran *kinds* that Fython supports?

E.g. if I have a Fortran module defining a math library supporting 32 and 64 bit (like) floats by means of `select_real_kind` Fortran built-in, Fython (importing this Fortran module) can handle (distinguish) the two kinds?

Thank you very much for sharing your great work.

My best regards.

**Comment by nicolasessisbreton** [comment]
Dear Stefano,

Sure, you can see here

 https://github.com/nicolasessisbreton/fython/blob/master/example/select_real_kinds/select_real_kinds_test.py

You can write any arguments after the intrinsic type
    real(16)

**Comment by szaghi** [comment]
@nicolasessisbreton wonderful! Great work!
