### ISSUE TITLE
Standard(s)

### ISSUE THREAD

**Issue by szaghi** [nicolasessisbreton/fython#2]
Dear Nicolas,

I am not able to understand which Fortran standard(s) Fython supports.

I am developing only in modern idioms (2003 and 2008), so before trying Fyghon I would like to know if Fython support things like *abstract type* and *coarrays*.

Thank you very much.

**Comment by nicolasessisbreton** [comment]
Dear Stefano,

Abstract types and coarrays are not yet supported.
I gave more details in my google clf reply.

**Comment by szaghi** [comment]
@nicolasessisbreton :ok_hand: thank you.
