### ISSUE TITLE
fails to run inside virtualenv

### ISSUE THREAD

**Issue by freevryheid** [nicolasessisbreton/fython#4]
suspect paths become screwed:

In [1]: import fython as fy
/bin/sh: ifort: command not found

In [2]: fy.hello()
---------------------------------------------------------------------------
module_not_found                          Traceback (most recent call last)
<ipython-input-2-251be62f0a73> in <module>()
----> 1 fy.hello()

/home/grassy/fy/lib/python3.5/site-packages/fython/hello/hello.py in hello()
      6                 url = 'fython.hello.hello',
      7                 force = 0,
----> 8                 release = 0,
      9 	)
     10 

/home/grassy/fy/lib/python3.5/site-packages/fython/load/load.py in load(url, release, force, verbose, run_main)
     18                 release = release,
     19                 force = force,
---> 20                 verbose = verbose,
     21 	)
     22 

/home/grassy/fy/lib/python3.5/site-packages/fython/kompile/kompile.py in kompile(url, cwd, release, force, verbose)
     11         stack = Stack(release, cwd, force, verbose)
     12 
---> 13         stack.load(fytbk.url, cwd)
     14 
     15         stack.load(url, cwd, is_target=1)

/home/grassy/fy/lib/python3.5/site-packages/fython/kompile/stack.py in load(s, url, cwd, fy_parent, is_target)
     49                                 cwd = cwd,
     50                                 ext = exts.importable,
---> 51                                 release = s.release,
     52 			)
     53                 url.fy_parent = fy_parent

/home/grassy/fy/lib/python3.5/site-packages/fython/config/url.py in __init__(s, url, cwd, ext, path_only, skip_if_not_found, packagebol, release)
     41                         s.relative()
     42                 else:
---> 43                         s.fully_qualified()
     44 
     45         def relative(s):

/home/grassy/fy/lib/python3.5/site-packages/fython/config/url.py in fully_qualified(s)
     72                                 return
     73 
---> 74                 s.throw_module_not_found()
     75 
     76         def set_filename(s, target):

/home/grassy/fy/lib/python3.5/site-packages/fython/config/url.py in throw_module_not_found(s)
    199                         return
    200                 else:
--> 201                         s.throw(err.module_not_found)
    202 
    203         @property

/home/grassy/fy/lib/python3.5/site-packages/fython/config/url.py in throw(s, error)
    179                 b += 'extensions considered:'
    180                 b += ', '.join(s.exts)
--> 181                 raise(error(b))
    182 
    183         def get_dotted_tree(s):

module_not_found: 
module not found
url fython.traceback.traceback
working directory '/home/grassy/fy/lib/python3.5/site-packages/fython/hello'
extensions considered:
/__init__.fy, .fy, .f, .fort, .f77, .f90, .f03, .f08, .F, .F77, .F90, .F03, .F08, .FORT, .so, /__init__.py, .py

**Comment by nicolasessisbreton** [comment]
I'm suggesting a potential fix, I will look more deeply into the issue soon.

It seems that ifort is not found within your virtual environment.
Make sure to source ifort before launching the virtualenv

$ source /opt/intel/bin/compilervars.sh intel64
$ (launch virtualenv)

**Comment by freevryheid** [comment]
yep, noticed that - but I no longer have ifort installed, only gfortan. 
Debugging the problem shows the module not found in:
`
def fully_qualified(s):
		s.dotted = s.url
		s.dotted_tree = s.get_dotted_tree()

		s.set_filename(s.dotted)

		for root in sys.path:
			root = abspath(root)
			if s.find(root):
				return

		s.throw_module_not_found()
`
The "find" proc generates a suspect path.

**Comment by nicolasessisbreton** [comment]
I just tried with virtualenv, on my machine it works. 
Make sure you setup a python3 environement.
I did:

#!/bin/bash
sudo pip3 install virtualenv
cd Desktop
virtualenv -p python3 a
cd a
cd bin
source activate
cd ..
git clone https://github.com/nicolasessisbreton/fython.git
cd fython
python3 setup.py develop
python3 # launch a python session

# python session
import fython
fython.hello()

output:
'Welcome to Fython. See the build products in ~/Desktop/a/fython/fython/hello/__pycache__/fycache'

**Comment by freevryheid** [comment]
Thanks - working now. Time to play :)
